#! /usr/bin/env python

import os.path

import numpy as np
import json
from glob import glob
import datetime as dt

from libcomcat.search import get_event_by_id
import urllib.request

from impactutils.io.smcontainers import ShakeMapOutputContainer
from mapio.grid2d import Grid2D
from mapio.geodict import GeoDict

# For plotting
from impactutils.colors.cpalette import ColorPalette
import matplotlib.pyplot as plt
palette = ColorPalette.fromPreset('mmi')

hdf_dir = './hdf'
outputfile = './atlas_metadata_1906.json'

print('Finding HDF files in directory ./hdf   ....')
allfiles = glob('./hdf/*/*_shake_result.hdf')
print('Done.')

c=0
eventdata={}
for hdf_file in allfiles:
    c+=1
    evid=hdf_file.split('/')[2].split('_')[0]

    print('Examining',hdf_file)
    container = ShakeMapOutputContainer.load(hdf_file)
    metadata=container.getMetadata()['input']['event_information']
    eventdata[evid]=metadata

# Now write output

with open(outputfile,'w') as f:
    json.dump(eventdata,f,indent=4)

